vars: {
  d2-config: {
     theme-id: 1
  }
}
D3: WhatModelFile
D4: ProcessObjects
D5: DataObjects
D6: ParseErrorList
D8: HierarchicalSystemGraph
D10: D2DiagramCode
D12: DataFlowDiagram
P2: ParseWhatNotHowModelFile
P2.shape: Hexagon
P7: AssembleGraphs
P7.shape: Hexagon
P9: D2CodeFromSystemGraphs
P9.shape: Hexagon
P11: GenerateDataFlowSVG
P11.shape: Hexagon
D3 -> P2
P2 -> D4
P2 -> D5
P2 -> D6 {style: {stroke-dash: 3}}
D4 -> P7
D5 -> P7
P7 -> D8
D8 -> P9
P9 -> D10
D10 -> P11
P11 -> D12
D6.style.stroke-dash: 3
