vars: {
  d2-config: {
     theme-id: 1
  }
}
D3: Config
D4: Data Frame
D5: Summary Stats
D6: Data Partitions
D8: Feature Importance
D9: Data Clusters
D10: Outlier List
D12: Data Dictionary
D13: I Data
D14: J Data
D16: K Data
D18: L Data
D19: M Data
D21: Optional Output
D23: Final Report
P2: Process 1
P2.shape: Hexagon
P7: Process 2
P7.shape: Hexagon
P11: Process 3
P11.shape: Hexagon
P15: Process 4
P15.shape: Hexagon
P17: Process 5
P17.shape: Hexagon
P17.style.multiple: true
P20: Process 6
P20.shape: Hexagon
P22: Process 7
P22.shape: Hexagon
D3 -> P2
D4 -> P2
P2 -> D5
P2 -> D6
D3 -> P7
D4 -> P7
P7 -> D8
P7 -> D9
P7 -> D10 {style: {stroke-dash: 3}}
D12 -> P11
D3 -> P11
D4 -> P11
P11 -> D13
P11 -> D14 {style: {stroke-dash: 3}}
D5 -> P15
D8 -> P15
P15 -> D16
D6 -> P17
D9 -> P17
P17 -> D18
P17 -> D19 {style: {stroke-dash: 3}}
D19 -> P20 {style: {stroke-dash: 3}}
D10 -> P20 {style: {stroke-dash: 3}}
D14 -> P20 {style: {stroke-dash: 3}}
P20 -> D21 {style: {stroke-dash: 3}}
D16 -> P22
D18 -> P22
P22 -> D23
D9.style.multiple: true
D6.style.multiple: true
D18.style.multiple: true
D4.style.multiple: true
D10.style.stroke-dash: 3
D19.style.stroke-dash: 3
D14.style.stroke-dash: 3
D21.style.stroke-dash: 3
