vars: {
  d2-config: {
     theme-id: 1
  }
}
D3: Optimal_DV_Values
D4: Constraint_Relaxation_Info
D5: MIP_Error_List
D6: Gurobi_Model
D8: Objective_Function_Info
D9: Variable_Definition_Info
D10: Constraint_Info
D12: Model-ID-List
D13: KPI_by_Model_ID
D14: KPI-Level-Weights
P2: SolveGurobiModel
P2.shape: Hexagon
P7: BuildGurobiModel
P7.shape: Hexagon
P11: BuildObjectiveFunction
P11.shape: Hexagon
D6 -> P2
P2 -> D3
P2 -> D4 {style: {stroke-dash: 3}}
P2 -> D5 {style: {stroke-dash: 3}}
D8 -> P7
D9 -> P7
D10 -> P7
P7 -> D6
D12 -> P11
D13 -> P11
D14 -> P11
P11 -> D8
D5.style.stroke-dash: 3
D4.style.stroke-dash: 3
