vars: {
  d2-config: {
     theme-id: 1
  }
}
D2: Opt_MRD
D3: Optimal_DV_Values
D4: Constraint_Relaxation_Info
D5: MIP_Error_List
D6: Gurobi_Model
D9: Objective_Function_Info
D10: Variable_Definition_Info
D11: Constraint_Info
D13: Model-ID-List
D14: KPI_by_Model_ID
D15: KPI-Level-Weights
P7: SolveGurobiModel
P7.shape: Hexagon
P8: BuildGurobiModel
P8.shape: Hexagon
P12: BuildObjectiveFunction
P12.shape: Hexagon
D6 -> P7
P7 -> D3
P7 -> D4 {style: {stroke-dash: 3}}
P7 -> D5 {style: {stroke-dash: 3}}
D9 -> P8
D10 -> P8
D11 -> P8
P8 -> D6
D13 -> P12
D14 -> P12
D15 -> P12
P12 -> D9
D4.style.stroke-dash: 3
D5.style.stroke-dash: 3
